spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sb_reporting_db
    username: sb_reporting
    password: SbReporting123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
